name: CI

on:
  push:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: php-actions/composer@v6
    - name: PHPUnit tests
      uses: php-actions/phpunit@v3
      with:
        configuration: phpunit.xml
        memory_limit: 256M
